packages:
  - packages/*
allowBuilds:
  '@parcel/watcher': set this to true or false
  electron: set this to true or false
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
onlyBuiltDependencies:
  - '@tosuapp/lazer-calculator'
  - electron
  - esbuild
