packages:
  - packages/*
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - electron-winstaller
onlyBuiltDependencies:
  - '@jellybrick/ffi-napi'
  - '@jellybrick/ref-napi'
  - '@tosu/pp'
  - electron
  - esbuild
overrides:
  tosu: link:packages/tosu
