name: PR-check

on:
  pull_request:

concurrency:
  group: lint-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    if: |
      !contains(github.event.pull_request.labels.*.name, 'skip ci') &&
      !contains(github.event.pull_request.labels.*.name, 'skip-ci') &&
      !contains(github.event.pull_request.title, '[skip ci]') &&
      !contains(github.event.pull_request.body, '[skip ci]')
    runs-on: ubuntu-latest
    #runs-on: windows-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Install Bun 🔧
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install Deps 🔧
        run: bun install --frozen-lockfile

      - name: Lint PR (prettier)
        run: bun run prettier:ci

      - name: Lint PR (eslint)
        run: bun run lint:ci

      - name: Test
        run: bun test